- name: Create infra list
  set_fact:
   infra_hostnames: []

- name: Set infras hostname
  set_fact:
    infra_hostnames: "{{ infra_hostnames + [ 'infra%02d'|format(item|int)+'.'+domain ] }}"
  loop: "{{ range(1, number_of_infras + 1, 1)|list }}"


- name: Create machines
  include_role:
   name: machine-azure
  vars:
   machine_type: "{{ infra_machine_type }}"
   group_var: infras
   asazure: infrasavailabilityset
  with_items: "{{ infra_hostnames }}"



